/* Generated By:JavaCC: Do not edit this line. JaggerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JaggerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 4;
  /** RegularExpression Id. */
  int DIGIT = 5;
  /** RegularExpression Id. */
  int STRING = 6;
  /** RegularExpression Id. */
  int CHAR = 7;
  /** RegularExpression Id. */
  int KEYLET = 8;
  /** RegularExpression Id. */
  int KEYIN = 9;
  /** RegularExpression Id. */
  int KEYEND = 10;
  /** RegularExpression Id. */
  int EOL = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<NUMBER>",
    "<DIGIT>",
    "<STRING>",
    "<CHAR>",
    "\"let\"",
    "\"in\"",
    "\"end\"",
    "\"\\n\"",
    "\"<\"",
    "\">\"",
    "\"=\"",
    "\"<=\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"print(\"",
    "\"if \"",
    "\" then \"",
    "\" else \"",
  };

}
